site_name: XTS Framework Documentation

nav:
  - Home: index.md
  - Tasks: 
      - Overview: Tasks/Tasks.md
  - Hardware:
      - Overview: Hardware/Hardware.md
  - Mover:
      - Overview: Mover/Mover Overview.md
      - Mover Class: Mover/Mover Class.md

